# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oii4SwSsaPvbN9dLvBz4hA6GymRgPF_o
"""

!pip install transformers datasets accelerate peft scikit-learn -q
!pip install sentence-transformers -q
!pip install faiss-cpu -q  # Use CPU version if GPU version fails
!pip install agentops -q

# Check if faiss-gpu works, otherwise use faiss-cpu
try:
    import faiss
    print(f"✓ FAISS version: {faiss.__version__}")
except:
    print("⚠️ Reinstalling FAISS...")
    !pip uninstall faiss faiss-gpu -y -q
    !pip install faiss-cpu -q
    print("✓ Using FAISS-CPU instead")

print("\n✅ Installation complete!")

import torch
import numpy as np
import pandas as pd
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    TrainingArguments,
    Trainer,
    DataCollatorForSeq2Seq
)
from datasets import Dataset, DatasetDict
from sentence_transformers import SentenceTransformer
import faiss
from peft import LoraConfig, get_peft_model, TaskType
from sklearn.metrics import accuracy_score, precision_recall_fscore_support
import warnings
warnings.filterwarnings('ignore')

# Check device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

def create_sample_dataset():
    """Create a simple news dataset"""
    news_data = [
        {"text": "The Federal Reserve raised interest rates by 0.25% to control inflation. The decision was unanimous.", "label": "authentic"},
        {"text": "NASA discovered evidence of water on Mars. The findings were published in Nature journal.", "label": "authentic"},
        {"text": "SHOCKING: Drink bleach to cure COVID-19! Miracle cure that doctors hate!", "label": "fake"},
        {"text": "BREAKING: Aliens exist! Government documents prove extraterrestrial contact for 50 years!", "label": "fake"},
        {"text": "United Nations announces climate summit to address global warming concerns.", "label": "authentic"},
        {"text": "Miracle pill melts 30 pounds in 1 week! No exercise needed!", "label": "fake"},
    ]

    dataset = Dataset.from_list(news_data)

    def format_instruction(example):
        instruction = f"Is this news authentic or fake? Article: {example['text']}"
        output = "authentic" if example['label'] == 'authentic' else "fake"
        return {'input_text': instruction, 'output_text': output}

    formatted = dataset.map(format_instruction)
    splits = formatted.train_test_split(test_size=0.2, seed=42)
    return DatasetDict({'train': splits['train'], 'validation': splits['test']})

dataset = create_sample_dataset()
print(f"Training: {len(dataset['train'])} samples")
print(f"Validation: {len(dataset['validation'])} samples")
print(f"\nExample: {dataset['train'][0]['input_text'][:100]}...")

def load_model_simple():
    """Simple model loading without LoRA for testing"""
    model_name = "google/flan-t5-small"

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)

    # Move to device
    model = model.to(device)

    print(f"✓ Model loaded: {model_name}")
    print(f"✓ Total parameters: {sum(p.numel() for p in model.parameters()):,}")

    return model, tokenizer

# Load the model
model, tokenizer = load_model_simple()
print(f"Model device: {next(model.parameters()).device}")

def simple_tokenize(examples):
    """Simplest tokenization for T5 - no as_target_tokenizer needed"""

    # Tokenize inputs
    model_inputs = tokenizer(
        examples['input_text'],
        truncation=True,
        padding='max_length',
        max_length=256
    )

    # Tokenize targets (T5 uses the same tokenizer for inputs and outputs)
    labels = tokenizer(
        examples['output_text'],
        truncation=True,
        padding='max_length',
        max_length=16
    )

    model_inputs['labels'] = labels['input_ids']
    return model_inputs

# Apply tokenization
print("Tokenizing datasets...")
tokenized = dataset.map(
    simple_tokenize,
    batched=True,
    batch_size=4
)

print("✓ Tokenization complete!")
print(f"Training samples: {len(tokenized['train'])}")
print(f"Validation samples: {len(tokenized['validation'])}")

!pip install -U transformers accelerate

!pip install -U transformers datasets accelerate -q

import torch
import transformers
from transformers import Trainer, TrainingArguments

print("Transformers version:", transformers.__version__)

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="no",   # ✅ works in older versions
    learning_rate=3e-4,
    per_device_train_batch_size=2,
    num_train_epochs=10,
    logging_steps=5,
    save_strategy="no",
    fp16=torch.cuda.is_available(),
    report_to="none"
)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

# Example dataset + tokenizer setup (REQUIRED)

from datasets import load_dataset
from transformers import AutoTokenizer

# Load dataset
dataset = load_dataset("imdb")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

# Tokenization function
def tokenize_function(example):
    return tokenizer(example["text"], truncation=True)

# Apply tokenization
train_tokenized = dataset["train"].select(range(1000)).map(tokenize_function, batched=True)

# 1. Install dependencies
!pip install transformers datasets accelerate -q


# 2. Imports
import torch
from transformers import Trainer, TrainingArguments, DataCollatorWithPadding

# ================================
# 3. Reduce dataset size (🔥 BIG IMPACT)
# ================================
train_tokenized = train_tokenized.select(range(500))   # ⬅️ reduce data

# Rename column if needed
if "label" in train_tokenized.column_names:
    train_tokenized = train_tokenized.rename_column("label", "labels")

# Convert to PyTorch format
train_tokenized.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)

# 4. Data collator
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)


# 5. Training arguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="no",
    learning_rate=3e-4,

    per_device_train_batch_size=8,
    num_train_epochs=3,

    logging_steps=10,
    save_strategy="no",
    fp16=torch.cuda.is_available(),
    report_to="none",
)
# 6. Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_tokenized,
    data_collator=data_collator,
)
# 7. Train
print("\n🚀 Starting training...")
print("=" * 50)

trainer.train()

print("=" * 50)
print("✅ Training complete!")

print("eval_dataset exists:", "eval_dataset" in globals())

from datasets import load_dataset

# Load dataset (if not already loaded)
dataset = load_dataset("imdb")

# Create eval dataset
eval_dataset = dataset["test"].select(range(200))

print(eval_dataset[0])

print(eval_dataset.column_names)

def predict(article):
    inputs = tokenizer(
        f"Classify the news as FAKE or REAL.\nArticle: {article}\nAnswer:",
        return_tensors="pt",
        truncation=True,
        max_length=256
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=3
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

def predict(article):
    inputs = tokenizer(
        article,
        return_tensors="pt",
        truncation=True,
        max_length=256,
        padding=True
    ).to(device)

    with torch.no_grad():
        outputs = model(**inputs)
        logits = outputs.logits
        predicted_class = torch.argmax(logits, dim=1).item()

    return "fake" if predicted_class == 0 else "real"

print("\n📊 Evaluation on validation set:")

correct = 0

for i, item in enumerate(eval_dataset):

    original_article = item["text"]

    pred = predict(original_article)   # 👈 uses the function above
    expected = item["label"]

    if pred == expected:
        correct += 1

accuracy = correct / len(eval_dataset)
print(f"\n✅ Validation Accuracy: {accuracy:.2%}")

print("\n" + "=" * 50)
print("🔍 INFORMATRUTH - Ready for testing!")
print("=" * 50)

try:
    custom_article = input("\nEnter a news article to analyze (or press Enter to skip): ").strip()
except:
    custom_article = ""

if custom_article:
    result = predict(custom_article).lower().strip()

    print(f"\n📰 Article: {custom_article}")
    print(f"🎯 Verdict: {result.upper()}")

    if "fake" in result:
        print("⚠️ This article appears to be misleading or false!")
    elif "real" in result:
        print("✅ This article appears to be authentic!")
    else:
        print("❓ Model output unclear")

